### ISSUE TITLE
`requirement.txt` needed to reproduce demo notebook.

### ISSUE THREAD

**Issue by davo417** [ericmetodiev/OmniFold#2]
Hello, I'm a researcher in particle physics and I've found this repo while searching for a machine learning approach to the unfolding problem.

I must say I was very impressed by the simple demos at [OmniFold](https://github.com/hep-lbdl/OmniFold) and I want to reproduce a more complex example, so I cloned this repo and tried to run the demo notebook.

Unfortunately I'm having problems with libraries like numpy and energyflow like deprecated `np.int` or non existent `DNN` attribute on `energyflow.archs`, this is more likely due to version differences between your environment and mine (I created my env by installing the required libraries by name and no pinned versions).

So I'm asking for a `requirements.txt` file or at least the versions of the major libraries used in order to reproduce the demo and perhaps contribute to it.

Also of there is a newer version of this method that'll be great too.

**Comment by bnachman** [comment]
Hi @davo417 !  Thank you for your interest in OmniFold.  This repo is not maintained anymore.  Please see https://github.com/hep-lbdl/OmniFold, where we will also be developing new, standardized software for OmniFold.  Your contributions are most welcome :)

**Comment by davo417** [comment]
Hello, I've already managed to solve the problem, just adding `dnn` to the import path, i.e `energyflow.archs.dnn.DNN`.
I'll continue in the recommended repo.
Thank'u.
